# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "keppel"
SPDX-PackageSupplier = "ospo@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/keppel"
SPDX-PackageComment = "The code in this project may include calls to APIs (\"API Calls\") of\n SAP or third-party products or services developed outside of this project\n (\"External Products\").\n \"APIs\" means application programming interfaces, as well as their respective\n specifications and implementing code that allows software to communicate with\n other software.\n API Calls to External Products are not licensed under the open source license\n that governs this project. The use of such API Calls and related External\n Products are subject to applicable additional agreements with the relevant\n provider of the External Products. In no event shall the open source license\n that governs this project grant any rights in or to any External Products,or\n alter, expand or supersede any terms of the applicable additional agreements.\n If you have a valid license agreement with SAP for the use of a particular SAP\n External Product, then you may make use of any API Calls included in this\n project's code for that SAP External Product, subject to the terms of such\n license agreement. If you do not have a valid license agreement for the use of\n a particular SAP External Product, then you may only make use of any API Calls\n in this project for that SAP External Product for your internal, non-productive\n and non-commercial test and evaluation of such API Calls. Nothing herein grants\n you any rights to use or access any SAP External Product, or provide any third\n parties the right to use of access any SAP External Product, through API Calls."

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json5",
  ".gitignore",
  ".hyperspace/pull_request_bot.json",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "build/**/*",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "certs/*.crt",
  "certs/README.md",
  "cmd/test/*.json",
  "docs/*.png",
  "docs/*.svg",
  "docs/*.json",
  "internal/**/fixtures/**/*.json",
  "internal/**/fixtures/**/*.sql",
  "internal/**/fixtures/**/*.sql.actual",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/cel.dev/cel-go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/alicebob/miniredis/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/databus23/goslo.policy/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/dlmiddlecote/sqlstats/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/go-redis/redis_rate/v10/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/golang-jwt/jwt/v5/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/gophercloud/gophercloud/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/gorilla/mux/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/golang-lru/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/klauspost/compress/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/lib/pq/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/opencontainers/distribution-spec/specs-go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/opencontainers/go-digest/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/opencontainers/image-spec/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_golang/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/redis/go-redis/v9/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/rs/cors/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-api-declarations/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-bits/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/spf13/cobra/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/timewasted/go-accept-headers/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/go.podman.io/image/v5/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.xyrillian.de/gg/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.xyrillian.de/oblast/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.xyrillian.de/schwift/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/cel.dev/expr/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/antlr4-go/antlr/v4/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/beorn7/perks/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/bsm/ginkgo/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/bsm/gomega/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/cespare/xxhash/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/containers/libtrust/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/containers/ocicrypt/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/davecgh/go-spew/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = [
  "vendor/github.com/docker/go-units/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/gofrs/uuid/v5/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/google/go-cmp/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/inconshreveable/mousetrap/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/itchyny/gojq/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/itchyny/timefmt-go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/jpillora/longestcommon/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/json-iterator/go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/klauspost/cpuid/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/klauspost/pgzip/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kylelemons/godebug/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/mattn/go-sqlite3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/moby/moby/client/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/moby/sys/capability/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/moby/sys/mountinfo/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/moby/sys/user/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/modern-go/concurrent/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/modern-go/reflect2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/munnerz/goautoneg/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/opencontainers/runtime-spec/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/pmezard/go-difflib/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_model/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/common/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/procfs/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/rabbitmq/amqp091-go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/sirupsen/logrus/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/spf13/pflag/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/stretchr/testify/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/ulikunitz/xz/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/vbatts/tar-split/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/yuin/gopher-lua/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/zeebo/xxh3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/go.podman.io/storage/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.uber.org/atomic/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/goleak/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.yaml.in/yaml/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.yaml.in/yaml/v3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/golang.org/x/exp/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sys/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/text/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/google.golang.org/genproto/googleapis/api/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/google.golang.org/genproto/googleapis/rpc/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/google.golang.org/protobuf/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"
