/******************************************************************************
*
*  Copyright 2020 SAP SE
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*
******************************************************************************/

package healthmonitorcmd

//This file contains a minimal complete Docker image (one blob with the image
//configuration and one manifest) as generated by the Dockerfile:
//
//    FROM scratch
//    LABEL foo=bar

const minimalImageConfiguration = `{"architecture":"amd64","config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{"foo":"bar"}},"container":"f8b234677745966fba9bc5a360bac229500b39d19084e5744731ed1bad49bf18","container_config":{"Hostname":"f8b234677745","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh","-c","#(nop) ","LABEL foo=bar"],"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{"foo":"bar"}},"created":"2020-02-18T13:26:55.921110889Z","docker_version":"19.03.5-ce","history":[{"created":"2020-02-18T13:26:55.921110889Z","created_by":"/bin/sh -c #(nop)  LABEL foo=bar","empty_layer":true}],"os":"linux","rootfs":{"type":"layers"}}`

const minimalManifest = `{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1092,
      "digest": "sha256:8e6b7af44d52984b99bf1f3f9587705983e9cf4d912d916668430456f4494c18"
   },
   "layers": []
}`

const minimalManifestMediaType = "application/vnd.docker.distribution.manifest.v2+json"
